// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkipbxbwsnjncmcpkzlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxraXBieGJ3c25qbmNtY3BremxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDcyNjcsImV4cCI6MjA2NTQ4MzI2N30.yIa02UI__4tgbnZLn7gYYt8ef7tq2DVSps_VNYWV60Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);